# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-06 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeluxeRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=255, unique=True)),
                ('availability', models.IntegerField(default=1)),
                ('student', models.IntegerField(default=0)),
                ('dept', models.IntegerField(default=0)),
                ('_id', models.CharField(default='', max_length=255)),
                ('mobile_num', models.IntegerField(default=0)),
                ('guest_name', models.CharField(default='', max_length=255)),
                ('guest_num', models.IntegerField(default=0)),
                ('check_in', models.CharField(default='', max_length=255)),
                ('check_out', models.CharField(default='', max_length=255)),
                ('relation', models.CharField(default='', max_length=255)),
                ('purpose', models.CharField(default='', max_length=255)),
                ('food', models.IntegerField(default=0)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=255, unique=True)),
                ('availability', models.IntegerField(default=1)),
                ('student', models.CharField(default='', max_length=255)),
                ('dept', models.IntegerField(default=0)),
                ('_id', models.CharField(default='', max_length=255)),
                ('mobile_num', models.IntegerField(default=0)),
                ('guest_name', models.CharField(default='', max_length=255)),
                ('guest_num', models.IntegerField(default=0)),
                ('check_in', models.CharField(default='', max_length=255)),
                ('check_out', models.CharField(default='', max_length=255)),
                ('relation', models.CharField(default='', max_length=255)),
                ('purpose', models.CharField(default='', max_length=255)),
                ('food', models.IntegerField(default=0)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
